from .config_so100_follower import SO100FollowerConfig, SO100FollowerEndEffectorConfig
from .config_so100_dual_follower import SO100DualFollowerConfig, SO100DualFollowerEndEffectorConfig
from .so100_follower import SO100Follower
from .so100_follower_end_effector import SO100FollowerEndEffector
from .so100_dual_follower import SO100DualFollower

# Module-level import for registration
so100_dual_follower = SO100DualFollower
